# Generated by Django 4.0.4 on 2022-05-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
