# Generated by Django 4.0.4 on 2022-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
