# Generated by Django 4.0.4 on 2022-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_word_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default='', max_length=255),
        ),
    ]
