# Generated by Django 4.0.4 on 2022-05-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_deck_title_alter_word_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='definition',
            field=models.CharField(default='', max_length=255),
        ),
    ]
