# Generated by Django 4.0.4 on 2022-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_word_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
