# Generated by Django 4.0.4 on 2022-05-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_date_word_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date_started',
            field=models.DateField(),
        ),
    ]
