# Generated by Django 4.0.4 on 2022-05-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_alter_word_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='date_started',
            field=models.DateField(auto_now=True),
        ),
    ]
