# Generated by Django 4.0.4 on 2022-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0009_date_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
