# Generated by Django 4.0.4 on 2022-05-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0010_alter_date_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(),
        ),
    ]
